In [1]:
import pandas as pd
import numpy as np
import seaborn as sn

In [4]:
df = sn.load_dataset("iris")

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
df["sepal_length"].head(3)

0    5.1
1    4.9
2    4.7
Name: sepal_length, dtype: float64

In [10]:
df.tail(3)

sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [11]:
df.nunique()

sepal_length    35
sepal_width     23
petal_length    43
petal_width     22
species          3
dtype: int64

In [13]:
df.sepal_length.unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [14]:
df.sepal_width.unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [15]:
df.petal_length.unique()

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9, 4. ,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8, 3.7,
       5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2])

In [16]:
df.petal_width.unique()

array([0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

In [17]:
df.sepal_width.value_counts()

3.0    26
2.8    14
3.2    13
3.4    12
3.1    11
2.9    10
2.7     9
2.5     8
3.5     6
3.3     6
3.8     6
2.6     5
2.3     4
3.6     4
3.7     3
2.4     3
2.2     3
3.9     2
4.4     1
4.0     1
4.1     1
4.2     1
2.0     1
Name: sepal_width, dtype: int64

In [18]:
df[["sepal_length", 'species']]

sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [19]:
df.loc[:15, "petal_length": "species"]

petal_length  petal_width species
0            1.4          0.2  setosa
1            1.4          0.2  setosa
2            1.3          0.2  setosa
3            1.5          0.2  setosa
4            1.4          0.2  setosa
5            1.7          0.4  setosa
6            1.4          0.3  setosa
7            1.5          0.2  setosa
8            1.4          0.2  setosa
9            1.5          0.1  setosa
10           1.5          0.2  setosa
11           1.6          0.2  setosa
12           1.4          0.1  setosa
13           1.1          0.1  setosa
14           1.2          0.2  setosa
15           1.5          0.4  setosa

In [26]:
df.select_dtypes(include= ["float", "object"])

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

LOC AND ILOC

In [22]:
df.loc[:15, ["petal_length", "sepal_length", "species"]]

petal_length  sepal_length species
0            1.4           5.1  setosa
1            1.4           4.9  setosa
2            1.3           4.7  setosa
3            1.5           4.6  setosa
4            1.4           5.0  setosa
5            1.7           5.4  setosa
6            1.4           4.6  setosa
7            1.5           5.0  setosa
8            1.4           4.4  setosa
9            1.5           4.9  setosa
10           1.5           5.4  setosa
11           1.6           4.8  setosa
12           1.4           4.8  setosa
13           1.1           4.3  setosa
14           1.2           5.8  setosa
15           1.5           5.7  setosa

CONDITIONAL RETRIEVING

In [42]:
df[df.sepal_length >=  7.5][["sepal_length", "species"]]

sepal_length    species
105           7.6  virginica
117           7.7  virginica
118           7.7  virginica
122           7.7  virginica
131           7.9  virginica
135           7.7  virginica

In [45]:
df.loc[(df["sepal_length"] >= 7.5), ["sepal_length", "species"]]

sepal_length    species
105           7.6  virginica
117           7.7  virginica
118           7.7  virginica
122           7.7  virginica
131           7.9  virginica
135           7.7  virginica

In [48]:
df[df.species.str.contains(pat = "color")].count()

sepal_length    50
sepal_width     50
petal_length    50
petal_width     50
species         50
dtype: int64

In [49]:
df[df.species.str.startswith(pat = "virgin")].count()

sepal_length    50
sepal_width     50
petal_length    50
petal_width     50
species         50
dtype: int64

In [50]:

df[df.species.str.endswith(pat = "osa")].count()

sepal_length    50
sepal_width     50
petal_length    50
petal_width     50
species         50
dtype: int64